//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D3Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D3Data.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string D3Loc_de_DE {
            get {
                return ResourceManager.GetString("D3Loc_de_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Great Britain).
        /// </summary>
        public static string D3Loc_en_GB {
            get {
                return ResourceManager.GetString("D3Loc_en_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United States).
        /// </summary>
        public static string D3Loc_en_US {
            get {
                return ResourceManager.GetString("D3Loc_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string D3Loc_es_ES {
            get {
                return ResourceManager.GetString("D3Loc_es_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español (Mexican).
        /// </summary>
        public static string D3Loc_es_MX {
            get {
                return ResourceManager.GetString("D3Loc_es_MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string D3Loc_fr_FR {
            get {
                return ResourceManager.GetString("D3Loc_fr_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        public static string D3Loc_it_IT {
            get {
                return ResourceManager.GetString("D3Loc_it_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        public static string D3Loc_ko_KR {
            get {
                return ResourceManager.GetString("D3Loc_ko_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string D3Loc_pl_PL {
            get {
                return ResourceManager.GetString("D3Loc_pl_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string D3Loc_pt_PT {
            get {
                return ResourceManager.GetString("D3Loc_pt_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string D3Loc_ru_RU {
            get {
                return ResourceManager.GetString("D3Loc_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string D3Loc_zh_CN {
            get {
                return ResourceManager.GetString("D3Loc_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正體中文.
        /// </summary>
        public static string D3Loc_zh_TW {
            get {
                return ResourceManager.GetString("D3Loc_zh_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string D3Server_CN {
            get {
                return ResourceManager.GetString("D3Server_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string D3Server_EU {
            get {
                return ResourceManager.GetString("D3Server_EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea.
        /// </summary>
        public static string D3Server_KR {
            get {
                return ResourceManager.GetString("D3Server_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan.
        /// </summary>
        public static string D3Server_TW {
            get {
                return ResourceManager.GetString("D3Server_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America.
        /// </summary>
        public static string D3Server_US {
            get {
                return ResourceManager.GetString("D3Server_US", resourceCulture);
            }
        }
    }
}
